# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: gradle cmd Action
      uses: eskatos/gradle-command-action@v1
      with:
        wrapper-cache-enabled: false
        dependencies-cache-enabled: false
        configuration-cache-enabled: false
        #gradle-version: 6.8.3
        gradle-version: wrapper	# The Gradle wrapper's version (default, useful for matrix builds)
        #gradle-version: current	# The current stable release
        ###arguments: build

#    - name: Grant execute permission for gradlew
#      run: chmod +x gradlew
#    - name: Build with Gradle
#      run: ./gradlew build

    - name: upload-artifact jar-artifact${{ matrix.node-version }}
      uses: 'actions/upload-artifact@v2'
      with:
        name: jar-artifact${{ matrix.node-version }}
        #path: '**/*.jar'
        path: '**/pcldumper/**'
    - name: upload-artifact *-*-all.jar${{ matrix.node-version }}
      uses: 'actions/upload-artifact@v2'
      with:
        name: shadowJar-artifact${{ matrix.node-version }}
        #path: '**/*.jar'
        #path: '**/pcldumper/**'
        path: 'pcldumper/build/libs/*-*-all.jar'
    - name: ls -latr ./
      run: ls -latr ./
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_COMPRESS: xz
          GHR_PATH: build/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
